name: CI/CD PIPELINE

on:
  push:
    branches: ["sanjeev-deployment"]
  pull_request:
    branches: ["sanjeev-deployment"]

jobs:
  test:
    runs-on: ubuntu:22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup JDK 17
      uses: actions/setup-java@17
      with:
        java-version: '17'
        distribution: 'coretto'
    
    - name: Run test using gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test